IF EXISTS (SELECT 1 FROM app.SchemaMigrations WHERE MigrationId = '0001_core')
    THROW 50000, 'Migration already applied', 1;

BEGIN TRAN;

CREATE TABLE app.Tenants (
    TenantId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name NVARCHAR(200) NOT NULL,
    Subdomain NVARCHAR(100) NOT NULL UNIQUE,
    CustomDomain NVARCHAR(255),
    SubscriptionStatus NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE TABLE app.CmsUsers (
    CmsUserId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CognitoUserId NVARCHAR(100) NOT NULL,
    Role NVARCHAR(50) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (TenantId) REFERENCES app.Tenants(TenantId)
);

CREATE TABLE app.Customers (
    CustomerId UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    TenantId UNIQUEIDENTIFIER NOT NULL,
    CognitoUserId NVARCHAR(100),
    Email NVARCHAR(255) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (TenantId) REFERENCES app.Tenants(TenantId),
    UNIQUE (TenantId, Email)
);

INSERT INTO app.SchemaMigrations VALUES
('0001_core', SYSDATETIME(), SUSER_SNAME(), 'Core tenancy & users');

COMMIT;